### ISSUE TITLE
Link to documentation in the original repositories

### ISSUE THREAD

**Issue by gabrieldansereau** [PoisotLab/SpeciesDistributionToolkit.jl#101]
@tpoisot The links to the documentation in the original repositories are broken, but I can't fix them since they have been archived. Raising this here since it would be a good thing to fix them until the monorepo is ready.

The links that need to be updated (in the README and the About section):
- [SimpleSDMLayers.jl](https://github.com/PoisotLab/SimpleSDMLayers.jl): https://poisotlab.github.io/SimpleSDMLayers.jl/stable/
- [GBIF.jl](https://github.com/PoisotLab/GBIF.jl): https://poisotlab.github.io/GBIF.jl/stable/
- [Fauxcurrences.jl](https://github.com/PoisotLab/Fauxcurrences.jl): https://poisotlab.github.io/Fauxcurrences.jl/

**Comment by tpoisot** [comment]
Good catch, the full documentation will point to a single website, so the problem will take care of itself (I've also update the README to point to this repo).
