### ISSUE TITLE
IO not exported?

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/SpeciesDistributionToolkit.jl#145]
Am I missing a new change to the API or are the files in `./src/io` not exported? Is there another way to read/write from disk?

**Comment by tpoisot** [comment]
They are loaded but not exported:

https://github.com/PoisotLab/SpeciesDistributionToolkit.jl/blob/572e0d534d8aa11a7f353590e9c83fb04c0efeee/src/SpeciesDistributionToolkit.jl#L32-L35

You can read manually with:

https://github.com/PoisotLab/SpeciesDistributionToolkit.jl/blob/572e0d534d8aa11a7f353590e9c83fb04c0efeee/src/io/geotiff.jl#L33

But you can also look at the way data from SimpleSDMDatasets are loaded, *e.g.*:

https://github.com/PoisotLab/SpeciesDistributionToolkit.jl/blob/572e0d534d8aa11a7f353590e9c83fb04c0efeee/src/integrations/datasets_layers.jl#L1

This might need a documentation mention when I port all of the docstrings to the website.

**Comment by tpoisot** [comment]
(also the reason not to export it is: I like it when other packages don't export the IO functions because it's a less important part of the process)

**Comment by gottacatchenall** [comment]
Ah okay I found the `save` method call but currently am getting an error trying to write a demo CHELSA layer with

```
a = convert(Float32, SimpleSDMPredictor(RasterData(CHELSA2, BioClim); layer=1, bbox...)))
SpeciesDistributionToolkit.save("tmp.tif", a)
```

which yields `ERROR: AssertionError: eltype(layer) <: Number`. 

In practice I can probably get around this by not using `similar(example_chelsa_layer)` calls to allocate memory, but is there a reason to not include a method to convert from the `RasterData` inner type as constructed above to be a `SimpleSDMPredictor{T} where T<:Number` for this case?

**Comment by tpoisot** [comment]
Yup that is indeed a likely bug, let me see.

**Comment by tpoisot** [comment]
OK I have opened a PR (#146) with a fix. The `eltype` has changed to facilitate the Tables/iteration interface, so there's an unexported function called `_inner_type` that does it.
