### ISSUE TITLE
Avoid using stride when clipping

### ISSUE THREAD

**Issue by gabrieldansereau** [PoisotLab/SpeciesDistributionToolkit.jl#150]
`clip` currently uses the stride, which might return approximation errors as in #144. 

@tpoisot had an idea to avoid using stride completely. Possibly using indices instead of coordinates?

**Comment by tpoisot** [comment]
I'm going to take a look at where we use `stride` internally, because I think we would get rid of so much edge cases by using indexing directly. I'll open a PR when I'm done.
