### ISSUE TITLE
geotiff driver kwarg 

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/SpeciesDistributionToolkit.jl#160]
In https://github.com/PoisotLab/SpeciesDistributionToolkit.jl/issues/30#issuecomment-1314513569 we discussed having an option to save with different geotiff drivers (needed for cloud-optimizer-geotiff (COG), see https://github.com/GEO-BON/biab-2.0/pull/40#discussion_r1117644273).

I don't think this is currently implemented, but would be as simple as moving the argument to this call https://github.com/PoisotLab/SpeciesDistributionToolkit.jl/blob/4c63b82698366e025612791b5f3c3e36005661df/src/io/geotiff.jl#L223 to be a keyword arg to `save` that is passed onto `_write_geotiff`

**Comment by gottacatchenall** [comment]
in fact it seems this is already implemented for the version of `write_geotiff` for multiple layers https://github.com/PoisotLab/SpeciesDistributionToolkit.jl/blob/4c63b82698366e025612791b5f3c3e36005661df/src/io/geotiff.jl#L203, just not for a single layer

**Comment by tpoisot** [comment]
Can you open a PR? I'll merge when I'm back at my computer.
