### ISSUE TITLE
downloaders break when imported as part of another module

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/SpeciesDistributionToolkit.jl#164]
When building download links, this bit of code https://github.com/PoisotLab/SpeciesDistributionToolkit.jl/blob/f243c405a0e0081c147feb9e267687c46e7d8539/SimpleSDMDatasets/src/providers/CHELSA/chelsa_future_v2.jl#L49 can (in some cases) build a misshapen URL because it trys to inject `$scenario_code` where   `scenario_code = replace(lowercase(string(S)), "_" => "-")`, and `S` is a SSP struct.

When I import the SDT in a module, e.g. `MyModule.jl`:
```
module MyModule
   using SpeciesDistributionToolkit
  
  function foo()
        SimpleSDMPredictor(
            RasterData(CHELSA2, BioClim),
            Projection(SSP370, GFDL_ESM4);
            layer="BIO1" ) 
  end   
   export foo
end
```

and run

```
include("MyModule.jl")
MyModule.foo()
```

fails because it trys to download a url with slug `2011-2040/SIMPLESDMDATASETS.GFDL-ESM4/simplesdmdatasets.ssp370/bio/CHELSA_bio1_2011-2040_simplesdmdatasets.gfdl-esm4_simplesdmdatasets.ssp370_V.2.1.tif`.

**Comment by gottacatchenall** [comment]
should be a simple fix to add 

```
Mstr, Sstr = map(x->convert(String, split(string(x), ".")[end]), [M,S])
stem = "CHELSA_bio$(var_code)_$(year_sep)_$(lowercase(replace(Mstr, "_" => "-")))_$(lowercase(Sstr))_V.2.1.tif"
```

**Comment by gottacatchenall** [comment]
this is also a problem for the paths, it creates a new dir in ENV["SDMLAYERS_PATH"] with `SimpleSDMDatasets`. as a prefix

**Comment by tpoisot** [comment]
Yeah, good call, it's going to do that for all providers, so I'm guessing we need an option to sanitize paths and URLs. It shouldn't be too complicated because we know exactly what string to remove.

**Comment by gottacatchenall** [comment]
makes sense. not sure if this works but if there are not other impacts it could be implemented at the `string(::SSP)` level.

also do you know of other traits that could have this issue?

**Comment by tpoisot** [comment]
I am working on this in #167 -- I think it's "simply" a matter of catching the module name in the string, and them replacing them by an empty string.
