### ISSUE TITLE
Phylopic.jl precompiles infinitely without stopping

### ISSUE THREAD

**Issue by asinghvi17** [PoisotLab/SpeciesDistributionToolkit.jl#223]
Hey!  I'm working on getting Makie to support displaying SVGs, and stumbled on phylopic and this repo.  Tried to install it but no luck - I got a bunch of these warnings:
```julia
┌ Phylopic
│  [pid 36124] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   tcp[16]            0x600001444000->0x107cdc9c0
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
│
│  [pid 36124] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   tcp[16]            0x600001444000->0x107cdc9c0
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
│
│  [pid 36124] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   tcp[16]            0x600001444000->0x107cdc9c0
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
│
│  [pid 36124] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   tcp[16]            0x600001444000->0x107cdc9c0
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
│
│  [pid 36124] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   tcp[16]            0x600001444000->0x107cdc9c0
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
│
```
and the package just kept precompiling, didn't stop after 5 minutes (but with low CPU usage).  

I was looking at using OpenAPI.jl to create an API wrapper for Phylopic, would you guys be interested in that?

FWIW, this is with Phylopic v0.0.3 and 
```julia
julia> versioninfo()
Julia Version 1.10.2
Commit bd47eca2c8a (2024-03-01 10:14 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 8 default, 0 interactive, 4 GC (on 8 virtual cores)
Environment:
  JULIA_NUM_THREADS = 8
```

**Comment by tpoisot** [comment]
Yeah, that's something I've observed when installing the package starting last week. I'm going to see what's triggering it, but I have not found the time yet.

If there ends up being an OpenAPI for phylopic, it would be great and I'd love to use it. The point of the package is more to be very user-facing (and we're not convering the entire API), but switching things internally for an OpenAPI wrapper would be awesome. 

Also: very good to hear that there's SVG support for Makie in the works 🎉

**Comment by asinghvi17** [comment]
Yep!  It's being prototyped at https://github.com/JuliaPlots/MakieTeX.jl/pull/46 and we've already made some cool plots with it (SVGs can be themed through CSS in librsvg, so this is pretty neat :D)

We've already made some cool plots with that:
![download-5](https://github.com/kadyb/vector-benchmark/assets/32143268/f60b8d38-8648-4583-82f8-6e4839da2900)

**Comment by tpoisot** [comment]
So this is specific to Julia v1.10, I'm going to see what the fix is and hopefully push it tonight.

**Comment by asinghvi17** [comment]
Interesting.  Thanks!  I monkeyed around with the OpenAPI generator a bit but it seems to have some issues - might be that the OpenAPI spec for Phylopic is incomplete.  Will try some more and get back to you but if it doesn't work it may not be worth the effort.

**Comment by tpoisot** [comment]
I think I got it -- If the tests run, I'll merge and tag a new release tomorrow.

**Comment by asinghvi17** [comment]
About the OpenAPI issue - https://github.com/JuliaComputing/OpenAPI.jl/issues/71?notification_referrer_id=NT_kwDOAep3pLQxMDI1NDMwOTg3MzozMjE0MzI2OA#issuecomment-2054264940 was the problem
