### ISSUE TITLE
Masking/segmentating layer based on vector

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/SpeciesDistributionToolkit.jl#231]
While building a BONs.jl casestudy, I realized it may be useful to be able to take vector features (e.g. political boundaries from [GADM.jl](https://github.com/JuliaGeo/GADM.jl),  which implements the Vector API from [GeoInterface](https://github.com/JuliaGeo/GeoInterface.jl)) and mask/segment an `SDMLayer` based on those features. I was able to do this relatively easily with `gdal_rasterize`, so I don't think the implementation would be too difficult 

More generally, it may be worth implementing the relevant GeoInterface API for for a raster for `SDMLayers`?

**Comment by tpoisot** [comment]
Yeah I think it makes tons of sense, and this is something we can do immediately after #229 is merged - I feel like this needs a stable way to have rasters with the CRS

**Comment by tpoisot** [comment]
Also reklevant: https://github.com/JuliaGeo/NaturalEarth.jl
