### ISSUE TITLE
`interpolate` layer to same CRS/size as target layer

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/SpeciesDistributionToolkit.jl#267]
it would be cool to have two layers, `foo` and `target`, and call `interpolate(foo, target)` to get a copy of `foo` converted to the same size and crs of `target`.

i think this would just be syntactic sugar for preexisting functionality?

**Comment by tpoisot** [comment]
that's 100% just `interpolate!(copy(target), foo)`, which we can add as a function

**Comment by tpoisot** [comment]
alright consider it donw
