### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/SpeciesDistributionToolkit.jl#27]
The revamped meta-package will need a new logo. Presumably something we can make a sticker out of.

**Comment by TanyaS08** [comment]
Colour palette restraints? Musical inspiration?🐾Am 2022-11-17 um 04:29 schrieb Timothée Poisot ***@***.***>:﻿
(tentatively assigning @TanyaS08 in case you have some spare inspiration)

**Comment by tpoisot** [comment]
Julia colors _of course_, and uhhhh Arctic Monkeys?

**Comment by TanyaS08** [comment]
![SDT_logo_D1](https://user-images.githubusercontent.com/61696728/203031160-1266b15f-84fc-4f55-8348-dd7190e0c927.png)
![SDT_logo_D2-01](https://user-images.githubusercontent.com/61696728/203031215-c5704d74-2606-49f5-aad0-ea96b4af946d.png)

**Comment by TanyaS08** [comment]
We be in A Tranquility Base Hotel and Casino Mood™

**Comment by TanyaS08** [comment]
![Uploading Untitled_Artwork 7.png…]()

**Comment by TanyaS08** [comment]
![Untitled_Artwork 7](https://user-images.githubusercontent.com/61696728/203031787-f9357df8-32df-4adf-bfcc-27b111777858.png)

**Comment by TanyaS08** [comment]
I like this take - typography TBD

![SDT_logo_D3-01](https://user-images.githubusercontent.com/61696728/203037650-4e18067f-8667-405b-b92b-b610293921bb.png)

**Comment by tpoisot** [comment]
![AddText_11-21-06.42.52.png](https://user-images.githubusercontent.com/579329/203180212-5fff1715-cb2c-4b6b-b6a0-35cb189b6140.png)

**Comment by TanyaS08** [comment]
If this evokes Edna Mode then I fear the other idea I noodled around with yesterday might just send you 😛

**Comment by TanyaS08** [comment]
Consider this a trigger warning

![SpeciesDistTB2](https://user-images.githubusercontent.com/61696728/203252359-296e3e04-954e-4b50-a369-6b015632e300.png)
![SpeciesDistTB](https://user-images.githubusercontent.com/61696728/203252393-af5ec00c-85ff-403e-9136-f5814b7b6cdf.png)

**Comment by TanyaS08** [comment]
> ![AddText_11-21-06.42.52.png](https://user-images.githubusercontent.com/579329/203180212-5fff1715-cb2c-4b6b-b6a0-35cb189b6140.png)

But that's just BORING

![SpeciesDistTB3](https://user-images.githubusercontent.com/61696728/203252587-b16d7202-e4e9-4289-a02d-3a66f2443343.png)
