### ISSUE TITLE
add a dispatch to the ConfusionMatrix functions

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/SpeciesDistributionToolkit.jl#290]
when called on a vector of CM, return mean + CI?

**Comment by gottacatchenall** [comment]
Any utility in using the CM type from [StatisticalMeasures.jl](https://juliaai.github.io/StatisticalMeasures.jl/dev/confusion_matrices/)?

**Comment by tpoisot** [comment]
meh - what's in there works well enough that there's no need to overthink it, I guess
