### ISSUE TITLE
Potential performance improvement for masking a vector of polygons

### ISSUE THREAD

**Issue by gottacatchenall** [PoisotLab/SpeciesDistributionToolkit.jl#342]
Right now the only `mask!` dispatch that exists for masking using polygons is `mask!(::SDMLayer, feature::GeoJSON.Feature)`

The most computationally expensive part of `mask!` is `change_inclusion!` https://github.com/PoisotLab/SpeciesDistributionToolkit.jl/blob/5570d3b59d8009cdb4b06c520bf162f1b8b8f27d/src/polygons/polygons.jl#L35

which, if we want to mask a `layers::Vector{SDMLayer}`, has to be done via `[mask(l) for l in layers]`, resulting in `length(layers)` calls of `change_inclusion!`

Having separate dispatch for `mask!(::Vector{SDMLayer}, ::GeoJSON.Feature)` would allow only a single call to get the inclusion mask for the polygon, which would speed up batch masking a fair bit

**Comment by tpoisot** [comment]
definitely - the way I'm doing it is to run the polygon based version on the first layer and then use the polygon masking method, which is faster

open a PR?

**Comment by gottacatchenall** [comment]
> open a PR?

#343
