### ISSUE TITLE
The order of arguments to read/save geotiffs make no sense

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/SpeciesDistributionToolkit.jl#38]
As per #30 -- the arguments to read/write geotiffs should follow the convention of *e.g.* `CSV.write`.

**Comment by tpoisot** [comment]
(this shouldn't be its own PR, it must be solved as part of #30)

**Comment by gottacatchenall** [comment]
Just a note that `CSV` breaks the (source, sink) argument rule in the same way as `geotiff`, where the `read` function takes arguments as (source,sink), `CSV.read("path.csv", DataFrame)`, but not for (sink,source) for `write`, e.g.: CSV.write("data.csv", df)

I'm not sure if this has been discussed in the Julia dev ecosystem, maybe there is a reason for it?

**Comment by tpoisot** [comment]
I think the rationale is: what gets modified is used first, so you write to a file (first arg). If you were to write to something already there, it would probably be `read!(obj, "source.csv")`. The idiomatic syntax to read now is `DataFrame(CSV.File("path"))` anyways, which solves this in a different way...

I am 97% sure I got the order of arguments from `CSV` back when I wrote the `geotiff` function,
